//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsImg
    {
        public int GoodsImg_id { get; set; }
        public string GoodsImg_thumbone { get; set; }
        public string GoodsImg_thumbone_big { get; set; }
        public string GoodsImg_thumbtwo { get; set; }
        public string GoodsImg_thumbtwo_big { get; set; }
        public string GoodsImg_thumbthree { get; set; }
        public string GoodsImg_thumbthree_big { get; set; }
        public string GoodsImg_detail { get; set; }
        public Nullable<int> Goods_id { get; set; }
        public string Goods_color { get; set; }
    }
}
