//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsE
    {
        public int GoodsE_Id { get; set; }
        public Nullable<int> Goods_count { get; set; }
        public string Goods_Color { get; set; }
        public string Goods_CodeNumber { get; set; }
        public Nullable<int> GoodsInfo_Id { get; set; }
    }
}
