//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logistics
    {
        public int Log_ID { get; set; }
        public string Log_name { get; set; }
        public string username { get; set; }
        public string Log_adrees { get; set; }
        public string Log_tel { get; set; }
        public string order_no { get; set; }
    }
}
