//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeInfo
    {
        public int announcement_id { get; set; }
        public string announcement_title { get; set; }
        public string announcement_content { get; set; }
        public Nullable<int> manager_id { get; set; }
        public Nullable<System.DateTime> announcement_time { get; set; }
        public Nullable<int> announcement_isDel { get; set; }
    }
}
