//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopManagement
    {
        public int cart_id { get; set; }
        public Nullable<System.DateTime> cart_addtime { get; set; }
        public string cart_photo { get; set; }
        public Nullable<int> cart_quantity { get; set; }
        public string cart_color { get; set; }
        public string cart_CodeNumber { get; set; }
        public Nullable<int> GoodsInfo_ID { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<decimal> cart_price { get; set; }
        public string cart_remark { get; set; }
        public Nullable<int> StoreInfo_ID { get; set; }
    }
}
