//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AddressInfo
    {
        public int address_Id { get; set; }
        public Nullable<int> address_isDefault { get; set; }
        public string address_street { get; set; }
        public string address_telephone { get; set; }
        public string address_name { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> address_isDel { get; set; }
        public string address_shengfen { get; set; }
        public string address_city { get; set; }
        public string address_qu { get; set; }
        public string address_detail { get; set; }
    }
}
