//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orderdetailsInfo
    {
        public int orderdetails_id { get; set; }
        public Nullable<decimal> orderdetails_totalprice { get; set; }
        public Nullable<int> orderdetails_quantity { get; set; }
        public string cart_color { get; set; }
        public string cart_CodeNumber { get; set; }
        public string cart_photo { get; set; }
        public string cart_remark { get; set; }
        public Nullable<decimal> orderdetails_unitprice { get; set; }
        public Nullable<int> GoodsInfo_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<decimal> orderdetails_price { get; set; }
        public Nullable<int> StoreInfo_ID { get; set; }
        public Nullable<int> UserInfo_id { get; set; }
    }
}
