//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnsImg
    {
        public int alternatePlay_id { get; set; }
        public string alternatePlay_img { get; set; }
        public Nullable<System.DateTime> alternatePlay_time { get; set; }
        public Nullable<int> alternatePlay_isDel { get; set; }
        public Nullable<int> GoodsInfo_ID { get; set; }
    }
}
