//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo_detail
    {
        public int detailId { get; set; }
        public Nullable<int> userid { get; set; }
        public string username { get; set; }
        public string user_nickname { get; set; }
        public string user_sex { get; set; }
        public string user_email { get; set; }
        public string user_telphone { get; set; }
        public string user_idcard { get; set; }
        public string user_qq { get; set; }
        public string user_photo { get; set; }
        public Nullable<decimal> user_money { get; set; }
        public string user_remark { get; set; }
    }
}
