//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int userid { get; set; }
        public string name { get; set; }
        public string user_password { get; set; }
        public Nullable<int> user_status { get; set; }
        public Nullable<System.DateTime> user_createTime { get; set; }
        public Nullable<int> store_id { get; set; }
    }
}
